baseURL = "http://sail1261.com/aic1418/"
languageCode = "en-au"
title = "AIC Discovery to Impact"

[[menu.main]]
  name = "This is the research section"
  weight = -110
  identifier = "research"
  url = "/research/"


[permalinks]
  posts = "/:section/:title/"
