baseURL = "https://2014-2018.australiaindonesiacentre.org/"
languageCode = "en-au"
title = "AIC Discovery to Impact"

[[menu.main]]
  name = "This is the research section"
  weight = -110
  identifier = "research"
  url = "/research/"


[permalinks]
  posts = "/:section/:title/"
